if ispc
    mex -v gw_IFWT.c ...
        wavelet_v7.c ...
        wavelet_mem_v7.c...
        wavelet_def_v7.c...
        cdotx.c ...
        ../Tools/MatlabIO.c ...        
        ../Tools/MatlabIO_WT.c ...
        ../Tools/MatlabIO_getfield.c ...
        ../Tools/myallocs.c ...
        ../Tools/prnmsg.c ...
        -I. -I../Tools/ ...
        -DMATLAB ... % -DNoThreads
        OPTIMFLAGS="$OPTIMFLAGS /arch:SSE2"
elseif isunix  
    mex -v gw_IFWT.c ...
        wavelet_v7.c ...
        wavelet_mem_v7.c...
        wavelet_def_v7.c...
        cdotx.c ...
        ../Tools/MatlabIO.c ...        
        ../Tools/MatlabIO_WT.c ...
        ../Tools/MatlabIO_getfield.c ...
        ../Tools/myallocs.c ...
        ../Tools/prnmsg.c ...
        -I. -I../Tools/ ...
        -DMATLAB ... %  -DNoThreads ...
        CFLAGS='\$CFLAGS -fopenmp -Wall' LDFLAGS='\$LDFLAGS -fopenmp' ...
        COPTIMFLAGS='-O2 -march=native -DNDEBUG' LDOPTIMFLAGS='-O2 -march=native'
end
